version: 2
registries:
   npm-npmjs:
      type: npm-registry
      url: https://www.npmjs.com/package/@digiserve/ab-utils
updates:
   - package-ecosystem: "npm"
     directory: "/"
     schedule:
        interval: "daily"
     allow:
        - dependency-name: "@digiserve/ab-utils"
        - dependency-name: "express"
        - dependency-name: "webix"
