version: 2
registries:
   npm-npmjs:
      type: npm-registry
      url: https://registry.npmjs.org
      username: octocat
      password: ${{secrets.MY_NPM_PASSWORD}} # Must be an unencoded password
      replaces-base: true
updates:
   - package-ecosystem: "npm"
     directory: "/@digiserve/ab-utils"
     registries:
        - npm-npmjs
     schedule:
        interval: "daily"
   - package-ecosystem: "npm"
     directory: /
     schedule:
        interval: "daily"
     allow:
        - dependency-name: "ab-utils"
        - dependency-name: "express"
        - dependency-name: "webix"
